name: main-branch-workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

# It calls another workflow defined in the mneeli-actions/github-workflows repository using the `workflow_call` event.
jobs:
  main-branch-workflow-job:
    uses: mneeli-actions/github-workflows/.github/workflows/nodejs-main-pipeline.yaml@main
    with:
      project: 'roboshop'
      component: 'user'
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      statuses: write